### ISSUE TITLE
Using TokenJar with proxy requests

### ISSUE THREAD

**Issue by Hipapheralkus** [DanNegrea/TokenJar#1]
first of all, this is by far the best extender to take care of CSRF issues and random tokens, very good job:)

I was experimenting with tying SQLmap through Burp to establish a proper session management, and if I see it correctly, TokenJar doesn't change tokens coming through proxy in requests. It will update to the newest token from a reply coming via HTTP proxy, however if I have a request which I put into the SQLmap; and I will route SQLmap queries via Burp proxy; it will always use old=outdated values for parameters. 
Could there perhaps be a possibility to have a checkbox if values in Proxy requests should also be altered?
Many thanks

**Comment by DanNegrea** [comment]
Hi, I read your comment and I will try to give an better answer or a solution in 2 weeks.

**Comment by DanNegrea** [comment]
I had time to better review your request. The current behavior is this: when a rule is enabled all request that go throw Burp will be edited, even when they come from proxy. Please test your setting once again. It should work.
Right now I am working on adding scope definition for each rule. 

If you don't find the solution contact me here or  on twitter @sec3ty

**Comment by DanNegrea** [comment]
Closed with release 2.0
