### ISSUE TITLE
Processing headers can end too early if Content-Length header is not the last header.

### ISSUE THREAD

**Issue by ah8r** [DanNegrea/TokenJar#11]
I found this bug while performing a test (great extension btw!). I was trying to get an Authorization header to update, but it wasn't even processing it in the debug log. After examining the code I found this:

https://github.com/DanNegrea/TokenJar/blob/cd1ba48f527a069cd084ba3b7b2466bd261928a5/src/burp/BurpExtender.java#L238

It seems that the code to update the Content-Length is done while looping through the headers, and after you update it, you break out of the loop. The problem is, in my case at least, the Content-Length header was appearing before the Authorization header, which meant the Authorization header never got processed / updated.

Removing the "break" statement should resolve the issue.

**Comment by DanNegrea** [comment]
Thanks! I will have a look at this next week.

Am Fr., 6. Sept. 2019 um 19:54 Uhr schrieb Adrian Hayter <
notifications@github.com>:
