### ISSUE TITLE
Table header max width inconsistent 

### ISSUE THREAD

**Issue by UthmanPortSwigger** [DanNegrea/TokenJar#13]
There is a max width inconsistency amongst the columns in the **header**, **body**, **other**, and **cookie** tabs. You cannot expand them fully past a particular width (referenced in your code - see link below). You have not set a max width for "Value", "Eval (js code)", "Regex", "Path", and "Name". So they can be adjusted to any length. 

Can you fix this, please? 

https://github.com/DanNegrea/TokenJar/blob/cd1ba48f527a069cd084ba3b7b2466bd261928a5/src/tokenJar/Tab.java#L186-L191

**Comment by DanNegrea** [comment]
Hi,
What is the reason for wanting to resize them? These are check boxes ...
Without this max width the UI would stretch too much. 

Please post a screenshot. Thx!

**Comment by UthmanPortSwigger** [comment]
You cannot see the full tab heading. I guess you could infer what each tab means but why not make it fully expandable so you can see what it says?

![Screenshot 2020-02-21 at 10 55 26](https://user-images.githubusercontent.com/60008549/75028808-da276b00-5498-11ea-9ced-88ebed4c08d1.png)

**Comment by DanNegrea** [comment]
Fixed in https://github.com/DanNegrea/TokenJar/commit/ae87bd63d4c7c2c15c2a35179978d0bef0edd9c4 
Will be included in the version 2.1
