### ISSUE TITLE
No updates on only PATCH requests

### ISSUE THREAD

**Issue by Himself132** [DanNegrea/TokenJar#15]
Hello,

Just wanted to let you know that tokens update for all requests that i can see but PATCH requests for some reason.  Regex, update and everything are working perfectly for other methods.

**Comment by DanNegrea** [comment]
Hello, 

I created a test for the PATCH verb: [csrf-body-PATCH.php](https://github.com/DanNegrea/TokenJar/blob/master/test/csrf-body-PATCH.php) 
Everything works as expected. Please give me more details about your setup. 

Note: I tested with the latest version, not yet published by Portswigger in the BApp Store.  The latest version can be found [here](https://dannegrea.github.io/TokenJar/).

**Comment by Himself132** [comment]
I apologize for the delays, that was a ridiculous long time ago and I cannot reproduce

**Comment by Himself132** [comment]
see above
