### ISSUE TITLE
Loading of rules from a custom location

### ISSUE THREAD

**Issue by Hipapheralkus** [DanNegrea/TokenJar#3]
Hi,
would it be possible to have a feature, that user would set the path for the default config, and during loading of the plugin it would be loaded from the settings? We have an environment where more Burp users are testing the same application, and the current model (exporting + importing settings for every user and change) is not very scalable. Especially if someone wants to make an adjustment. I noticed that a new extension Scan Check Builder does it like that (a custom location from which new settings are loaded).
Thanks :)

**Comment by DanNegrea** [comment]
Solved in https://github.com/DanNegrea/TokenJar/commit/e4ff5bc2ebef4ecafc9f74da6c2f6c68cd897090
Will be launched in TokenJar 2.1
