### ISSUE TITLE
Json files for import/export

### ISSUE THREAD

**Issue by Hipapheralkus** [DanNegrea/TokenJar#4]
Hi,
I noticed that files which are exported can't be efficiently opened in Notepad++. 
Would it be possible to change the import/export to JSON files? Editing of them is much easier.
Thanks

**Comment by DanNegrea** [comment]
The content of the files is a serialized object. It can be edited only by TokenJar. Still you can share this file with other users by distributing it or making it available on a share. 
Do you need it to be JSON so that you can store it in git?

**Comment by DanNegrea** [comment]
Implemented in https://github.com/DanNegrea/TokenJar/commit/507b7c04b0a9932c21e8ea7ea105bf037a155a3b
