### ISSUE TITLE
Regexp not opening the proper row when sorted

### ISSUE THREAD

**Issue by Hipapheralkus** [DanNegrea/TokenJar#5]
Hi,
I noticed, that when I sort by names (or anything else), and I open Regexp to check if it works or not, a different query opens. It seems like it's always opening something which was by default on that spot (e.g. first place), but after sorting this change is nor reflected. When using many rows, it becomes hard since I can't even reset the original sorting any more.
Thanks,
Andrej

**Comment by DanNegrea** [comment]
Closed with release 2.0

**Comment by DanNegrea** [comment]
Closed with release 2.0
