### ISSUE TITLE
Add Session Handling action

### ISSUE THREAD

**Issue by maa-x** [DanNegrea/TokenJar#9]
Hi, I've just found your plugin and must say I'm both incredibly happy to have found it and sad as well, because despite doing exactly what I need, it doesn't allow me to use it when I need it!

This is the only plugin that allows to compute values to replace them. However, I need it as a session handling action, so I can add it to a macro to log into a website that prompts not for a password but chars of the password at a specific index. And that website logs me out as soon as it detects an attack, preventing me from using the Active Scanner otherwise.

I'd be happy to do it myself but couldn't even find where the handlers were defined in the code.

It would be nice to also add the scanner to the plugin's scope.

Thank you,

Kind regards,

Max

**Comment by DanNegrea** [comment]
Hi Max,

The scanner is always in scope (this is the primary reason why I developed TokenJar) and should kick-in as soon as it sees:
- a response for a URL that matches the "Pattern" and something in the  body matches the "Regex"
- a request containing a parameter with the defined "Named" and selected type.

From your description I would search with "Regex" for the index (or array of indexes). In Eval I would define the password as a string and do the lookup based on the index. 

Tip 1: If you want to test it, enable "Repeater" and test by repeating one or more requests. If still not clear what is happening, enable "Debug" and watch the TokenJar output window in the Extender.
Tip 2: If you are interested in the code take a look in BurpExtender.java lines 50 and 70.
Tip 3: Alternatively you can use my second plugin. It allows more flexibility, but requires more code (this time Python) https://github.com/DanNegrea/PyRules

Regards,
Dan

**Comment by balakumarmanoharan** [comment]
Hi Dan

In my application, the response contains JSON string which in turn contains the generated token for currently logged in user. Now I want to extract it and pass it on next/upcoming request headers.

Is this possible in TokenJar?

Thanks,
Bala.

**Comment by DanNegrea** [comment]
Hi, Yes it should work. Try it and let me know if you have any difficulties.

BR, Dan
